<a href="https://colab.research.google.com/github/thdusqpf/verlan/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
vowels = ['a', 'e', 'i', 'o', 'u']

identical_pronunciation = { 'i' : ['i', 'y'],
                    'y' : ['y', 'u', 'eu'],
                    'e' : ['e', 'ai', 'eiz'],
                    'o' : ['o', 'au', 'eau'],
                    'u' : ['ou', 'aou'],
                    'f' : ['f', 'ph'],
                    'k' : ['c', 'cc', 'k', 'que', 'ch'],
                    'c' : ['q', 'que'],
                    's' : ['s', 'sc', 'se', 'c', 'x', 'ch'],
                    'z' : ['z', 's'],
                    't' : ['tte'],
                    'j' : ['ge']}

!pip install unidecode

import pandas as pd
from nltk.tokenize import SyllableTokenizer
from nltk import word_tokenize
import unicodedata
from unidecode import unidecode
#import alphabet

verlan = input()

def remove_accents(text):
    if isinstance(text, str):
        return unidecode(text)
    else:
        return text

def tokenize(text):
  ssp = SyllableTokenizer()
  return ssp.tokenize(text)

def remove_stopword(text):
  syllables = tokenize(text)
  first_index = 0
  last_index = len(syllables)-1

  for i in (first_index, last_index):
    last_alphabet_of_syllable = syllables[i][-1]
    number_of_vowels = sum(word.count(vowel))

    if (number_of_vowels>1 and last_alphabet_of_syllable == 'u'):
      syllables[i] = syllables[i].strip('u')
  return syllables

def switch_syllables(text):
  text.insert(0, text[-1])
  return text[:-1]

def handle_identical_pronounciation(text):
  possible_word_tree = []

  for alphabet in text:
    for key in identical_pronunciation.keys():
      if alphabet == key:
        for value in identical_pronunciation[key]:
          possible_word.append(text.replace(alphabet, value))
  print(possible_word)

verlan_without_accent = remove_accents(verlan)
verlan_without_accent_stopword = remove_stopword(verlan_without_accent)
switched_verlan_without_accent_stopword = switch_syllables(verlan_without_accent_stopword)
print(switched_verlan_without_accent_stopword)
preprocessed_verlan = handle_identical_pronounciation(switched_verlan_without_accent_stopword)

cimer


NameError: name 'word' is not defined

In [ ]:
space_letter = ' '
comma_letter = '\''
dash_letter = '-'
special_letter = '’'
special_letters = [space_letter, comma_letter, dash_letter,special_letter]

In [ ]:

first_big_id = ord('A')
last_big_id = ord('Z')
first_small_id = ord('a')
last_small_id = ord('z')

big = list(range(first_big_id, last_big_id + 1))
small = list(range(first_small_id, last_small_id + 1))

english_letter_list = [chr(num) for num in big + small]

english_letter_list.extend(special_letters)

idx2english = dict(enumerate(english_letter_list, 1)) #1부터 시작
print(idx2english.items())
english2idx = {v: k for k, v in idx2english.items()}

dict_items([(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H'), (9, 'I'), (10, 'J'), (11, 'K'), (12, 'L'), (13, 'M'), (14, 'N'), (15, 'O'), (16, 'P'), (17, 'Q'), (18, 'R'), (19, 'S'), (20, 'T'), (21, 'U'), (22, 'V'), (23, 'W'), (24, 'X'), (25, 'Y'), (26, 'Z'), (27, 'a'), (28, 'b'), (29, 'c'), (30, 'd'), (31, 'e'), (32, 'f'), (33, 'g'), (34, 'h'), (35, 'i'), (36, 'j'), (37, 'k'), (38, 'l'), (39, 'm'), (40, 'n'), (41, 'o'), (42, 'p'), (43, 'q'), (44, 'r'), (45, 's'), (46, 't'), (47, 'u'), (48, 'v'), (49, 'w'), (50, 'x'), (51, 'y'), (52, 'z'), (53, ' '), (54, "'"), (55, '-'), (56, '’')])


In [ ]:
import pandas as pd

xlsx = pd.read_excel('VerlanObjects_t.xlsx')
xlsx.to_csv('VerlanObjects_t.csv')

In [ ]:

import numpy as np
import pandas as pd

df = pd.read_csv('VerlanObjects_t.csv', encoding='utf-8')
del df['Unnamed: 0']
df.columns

Index(['Original', 'Verlan'], dtype='object')

In [ ]:

#Load X
verlan = df['Verlan'].apply(lambda x: np.array([english2idx[letter] for letter in x]))

verlan_df = pd.DataFrame(verlan)

X = pd.DataFrame(verlan_df['Verlan'].tolist()).values

#Replace nan to 0
X[np.isnan(X)] = 0
print(X)

[[ 3. 27. 35. ...  0.  0.  0.]
 [ 2. 31. 47. ...  0.  0.  0.]
 [18. 31. 28. ...  0.  0.  0.]
 ...
 [44. 31. 28. ...  0.  0.  0.]
 [29. 34. 31. ...  0.  0.  0.]
 [28. 38. 31. ...  0.  0.  0.]]


In [ ]:
X.shape

(356, 14)

In [ ]:
#Flip the input
X = np.flip(X, axis = 1)
X

array([[ 0.,  0.,  0., ..., 35., 27.,  3.],
       [ 0.,  0.,  0., ..., 47., 31.,  2.],
       [ 0.,  0.,  0., ..., 28., 31., 18.],
       ...,
       [ 0.,  0.,  0., ..., 28., 31., 44.],
       [ 0.,  0.,  0., ..., 31., 34., 29.],
       [ 0.,  0.,  0., ..., 31., 38., 28.]])

In [ ]:

#Load Y
original = df['Original'].apply(lambda x: np.array([english2idx[letter] for letter in x]))

original_df = pd.DataFrame(original)

Y = pd.DataFrame(original_df['Original'].tolist()).values

#Replace nan to 0
Y[np.isnan(Y)] = 0
print(Y)

[[ 1. 39. 31. ...  0.  0.  0.]
 [ 1. 44. 27. ...  0.  0.  0.]
 [ 1. 44. 27. ...  0.  0.  0.]
 ...
 [28. 41. 47. ...  0.  0.  0.]
 [28. 44. 27. ...  0.  0.  0.]
 [42. 41. 45. ...  0.  0.  0.]]


In [ ]:
Y.shape

(356, 19)

In [ ]:
#Split train & test & validation set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.3)

In [ ]:
from keras.layers import GRU  # GRU 레이어를 직접 임포트

# Parameters for the model and dataset
TRAINING_SIZE = 50000
VOCAB_SIZE = 12
INVERT = True
HIDDEN_SIZE = 200
BATCH_SIZE = 100
LAYERS = 2
MAX_EPOCHS = 1000
EMBEDDING_OUTPUT_SIZE = 128
# 이 부분은 X가 무엇인지에 따라 달라지므로, X를 적절히 정의해야 합니다.
# 예를 들어, X가 훈련 데이터의 입력 행렬이라면, 그에 따른 적절한 값을 설정해야 합니다.
MAX_SENT_LENGTH = X.shape[1] + 1

# 사용하고자 하는 RNN 레이어를 직접 지정
# 예시에서는 GRU를 사용하고 있으므로, 이를 직접 임포트하여 사용합니다.
RNN = GRU
stop_monitor = 'val_accuracy'  # 최신 버전에서는 'val_acc' 대신 'val_accuracy'를 사용
stop_delta = 0.0  # minimum delta before early stop (default = 0)
stop_epochs = 20    # how many epochs to do after stop condition (default = 0)


In [ ]:
from IPython.display import SVG, display
# TensorFlow 2.x에서의 Keras 모듈 경로 사용
from tensorflow.keras.utils import model_to_dot

def viz_model(model):
    display(SVG(model_to_dot(model, show_shapes=True).create(prog='dot', format='svg')))


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, TimeDistributed, Activation, RepeatVector, Embedding, Dropout

def build_model(embedding_input_dim,
                embedding_output_dim,
                embedding_input_length,
                maximum_input_length,
                hidden_size,
                maximum_output_length,
                encoder_layer_count,
                dropout_rate,
                output_classes_count,
                rnn_layer,
                summary_type=False):

    print('Build model...')
    RNN = rnn_layer

    model = Sequential()

    model.add(Embedding(
        input_dim=embedding_input_dim,
        output_dim=embedding_output_dim,
        input_length=embedding_input_length
    ))

    model.add(RNN(hidden_size, return_sequences=True, input_shape=(maximum_input_length, 123)))
    model.add(RNN(hidden_size))

    model.add(RepeatVector(maximum_output_length)) # 글자수 맥시멈

    for _ in range(encoder_layer_count):
        model.add(RNN(hidden_size, return_sequences=True))
        model.add(Dropout(dropout_rate))

    # For each of step of the output sequence, decide which character should be chosen
    model.add(TimeDistributed(Dense(output_classes_count)))
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy', # default: categorical_crossentropy
                  optimizer='adam', # default: adam, can try SGD, RMSprop
                  metrics=['accuracy'])



    if summary_type is False:
        pass
    elif str(summary_type).lower() == 'svg':
        viz_model(model)
    else:
        model.summary()

    return model

print('Done')

Done
